# This rule is not used by the project frp-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to frp.aureum.cloud resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "frp-operator.labels" . | nindent 4 }}
  name: exitserver-viewer-role
rules:
- apiGroups:
  - frp.aureum.cloud
  resources:
  - exitservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - frp.aureum.cloud
  resources:
  - exitservers/status
  verbs:
  - get
