apiVersion: v1
kind: Service
metadata:
  name: {{ include "frp-operator.fullname" . }}
  labels:
    {{- include "frp-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.port }}
  selector:
    {{- include "frp-operator.selectorLabels" . | nindent 4 }}